# Generated by Django 6.1 on 2026-08-19 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text="User's initial instruction or request")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('triage_category', models.CharField(blank=True, choices=[('direct_answer', 'Direct Answer'), ('web_search', 'Web Search'), ('rag_retrieval', 'RAG Retrieval'), ('calculation', 'Calculation'), ('sensitive_action', 'Sensitive Action (HITL)')], max_length=64, null=True)),
                ('output', models.TextField(blank=True, help_text='Final synthesized answer', null=True)),
                ('approval_prompt', models.TextField(blank=True, help_text='Description of action requiring user confirmation', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.agenttask')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
