# Generated by Django 6.1 on 2026-09-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='title',
            field=models.CharField(blank=True, help_text='Custom title or topic for this chat session', max_length=255, null=True),
        ),
    ]
